{
  inputs,
  pkgs,
  config,
  ...
}: let
  archives = import ../shared/pkgs/archives.nix {inherit pkgs;};
  core = import ../shared/pkgs/core.nix {inherit pkgs inputs;};
  devtools = import ../shared/pkgs/devtools.nix {inherit pkgs;};
  gui = import ../shared/pkgs/gui.nix {inherit pkgs inputs;};
  guilibs = import ../shared/pkgs/guilibs.nix {inherit pkgs;};
  network = import ../shared/pkgs/network.nix {inherit pkgs;};
  pythonpackages = import ../shared/pkgs/python.nix {inherit pkgs;};
  shellutils = import ../shared/pkgs/shellutils.nix {inherit pkgs;};
  system = import ../shared/pkgs/system.nix {inherit inputs pkgs;};
in {
  imports = [../shared/pkgs/fonts.nix];
  environment.systemPackages = with pkgs;
    archives
    ++ core
    ++ evtools
    ++ gui
    ++ guilibs
    ++ network
    ++ pythonpackages
    ++ shellutils
    ++ [  appimage-run
  appstream-glib
  stable.calibre
  kdePackages.breeze-icons
  gnome-icon-theme
  file-roller
  fuseiso
  gcolor3
  geocode-glib_2
  gmime3
  gnome-disk-utility
  gnome-font-viewer
  gnome-themes-extra
  gob2
  gparted
  graphite2
  gthumb
  gtk2-x11
  gtk3
  gtk3-x11
  gtk4
  gusb
  lcdf-typetools
  libappindicator-gtk3
  libglibutil
  libnotify
  libusb1
  libxdg_basedir
  mime-types
  mimetic
  nerd-font-patcher
  networkmanagerapplet
  pastel
  pavucontrol
  perl538Packages.CairoGObject
  psftools
  t1utils
  template-glib
  vscode-fhs
  wirelesstools
  wmctrl
  xclip
  xdg-desktop-portal
  xdg-launch
  xdgmenumaker
  xdotool
  xscreensaver
     cairo
  cairomm
  dbus-broker #gui tool
  dconf
  gdk-pixbuf
  gdk-pixbuf-xlib
  gnome.gvfs
  gobject-introspection
  gsettings-desktop-schemas
  gtk_engines
  libcanberra-gtk3 #system tool
  libpeas2
  libpeas
  libgudev
  libgee
  libgee
  libglibutil
  menu-cache #gui tool
  pango
  pangomm
  polkit_gnome
  python312Packages.cairosvg
  python312Packages.pyqt6
  python312Packages.qtpy
  rubyPackages.cairo-gobject
  rubyPackages.gdk_pixbuf2
  rubyPackages.gobject-introspection
  template-glib
  terminus_font #system tool
  vte-gtk4
  xclip #gui tool
  xfce.exo
  xfce.garcon
  xfce.libxfce4ui
  xfce.libxfce4util
  xfce.xfconf
  xorg-rgb
    bash-completion
  bat
  curl
  eza
  fd
  fzf
  fzy
  killall
  trash-cli
  libdbusmenu
  libdbusmenu-gtk3
  libinput

 afuse
 appstream
 appstream-glib
 automake
 avfs
 beep
 bintools
 brightnessctl #system tool
 cdrtools # for mkisofs
 comma
 csv2latex
 portaudio
 curtail
 dbus-broker
 dconf
 ddcui
 ddcutil
 deer
 didyoumean
 dosfstools
 edk2
 edk2-uefi-shell
 efibootmgr
 eggdbus
 exfatprogs
 fd
 gcc_latest
 gh
 ghostscript
 glib
 glibc
 gnome-keyring
 htop
 jdupes
 jq
 kconfig-frontends
 keyutils
 libgcc
 libgccjit
 libgnome-keyring
 libisoburn
 lm_sensors
 lshw
 massren
 mdds
 meson
 moreutils
 mtools
 neofetch
 nmon
 ntfs3g
 ntfsprogs
 opencl-clang
 openssl
 parallel
 pinentry-tty
 pmutils
 polkit_gnome
 procps
 ps_mem
 python312Packages.py-dmidecode
 renameutils
 ripgrep-all
 rnr
 shared-mime-info
 silver-searcher
 simpleTpmPk11
 slop
 smartmontools
 snappy
 sysctl
 sysfsutils
 sysprof
 sysstat
 systeroid
 sysvtools
 sysz
 template-glib
 testdisk
 trash-cli
 tree
 usbmuxd
 utillinux
 ventoy-full
 vgrep
 vimv
 wget
 whois
 wiper
 wmctrl
 wmic-bin
 wmutils-core
 wmutils-libwm
 wmutils-opt
 xclip
 xdg-dbus-proxy
 xdg-desktop-portal-gtk
 xdg-user-dirs
 xdg-utils
 xdotool
 xfontsel
 xgeometry-select
 xorg.fontalias
 xorg.fonttosfnt
 xorg.fontutil
 xorg.libxcb
 xorg.mkfontdir
 xorg.xbacklight
 xorg.xcbutil
 xorg.xcbutilerrors
 xorg.xcbutilimage
 xorg.xcbutilrenderutil
 xorg.xcbutilwm
 xorg.xconsole
 xorg.xev
 xorg.xev
 xorg.xhost
 xorg.xinit
 xorg.xkill
 xorg.xorgproto
 xorg.xprop
 xorg.xwininfo
 xorriso
 xsecurelock
 xsettingsd
 xss-lock

  _7zz
  advancecomp
  archivemount
  cpio
  crabz
  gnome-autoar
  gnutar
  libarchive
  lz4
  mozlz4a
  ouch
  p7zip-rar
  pigz
  pixz
  plzip
  pxz
  rar
  rarcrack
  xarchiver
  xz
  zip
  zlib-ng
  zstd
  cbfmt
  coreutils-full
  uutils-coreutils
  ccls
  sops
  age
  agenix-cli
  ssh-to-age

  clang-tools
  cmake
  commonsCompress
  dmg2img
  dnsutils
  libglibutil
  font-alias
  fcft
  ffmpeg-full
  figlet
  fontconfig
  ftgl
  minizip2
  networkmanager
  nmap
  papirus-folders
  pulseaudio
  tealdeer
  toilet
  ttfautohint
  actionlint
  any-nix-shell
  bc
  opencode
  prettier
  cloudflare-cli
  quictls
  bfg-repo-cleaner
  black
  treegen
  brotli
  cached-nix-shell
  clang
  direnv
  eslint_d
  fuse3
  gcc
  gccStdenv
  gist
  git
  glib
  glow
  gnutls
  imlib2Full
  inetutils
  just
  latex2html
  libclang
  libcxxStdenv
  libffi
  libglibutil
  libimobiledevice
  libpkgconf
  libtiff
  libtool
  lua-language-server
  lua51Packages.lua
  lua51Packages.luarocks
  lua5_1
  luabind
  luaformatter
  luajitPackages.inspect
  luajitPackages.ldbus
  luajitPackages.ldoc
  luajitPackages.lgi
  luajitPackages.lua
  luajitPackages.lua-messagepack
  luajitPackages.lua-protobuf
  luajitPackages.luarocks-nix
  luajitPackages.luasocket
  luajitPackages.std-_debug
  luajitPackages.std-normalize
  luajitPackages.stdlib
  luajitPackages.vicious
  luajitPackages.wrapLua
  nix-init
  pciutils
  pixcat
  pkg-config
  protobuf
  protobufc
  rmlint
  shfmt
  tree-sitter
  squashfs-tools-ng
  squashfsTools
  squashfuse
  vscode-langservers-extracted
  wkhtmltopdf-bin
  xorg.libX11
  xorg_sys_opengl
  yamllint
  zlib

]
}
