{
  inputs,
  pkgs,
  config,
  ...
}: let
  archives = import ../shared/pkgs/archives.nix {inherit pkgs;};
  core = import ../shared/pkgs/core.nix {inherit pkgs inputs;};
  devtools = import ../shared/pkgs/devtools.nix {inherit pkgs;};
  gui = import ../shared/pkgs/gui.nix {inherit pkgs inputs;};
  guilibs = import ../shared/pkgs/guilibs.nix {inherit pkgs;};
  network = import ../shared/pkgs/network.nix {inherit pkgs;};
  pythonpackages = import ../shared/pkgs/python.nix {inherit pkgs;};
  shellutils = import ../shared/pkgs/shellutils.nix {inherit pkgs;};
  system = import ../shared/pkgs/system.nix {inherit inputs pkgs;};
in {
  imports = [../shared/pkgs/fonts.nix];
  environment.systemPackages = with pkgs; [
    _7zz
    afuse
    age
    agenix-cli
    any-nix-shell
    archivemount
    brightnessctl #system tool
    cairo
    cairomm
    coreutils-full
    cpio
    dbus-broker #gui tool
    dconf
    ddcui
    ddcutil
    dosfstools
    eggdbus
    exfatprogs
    eza
    fcft
    fd
    ffmpeg-full
    file-roller
    font-alias
    fontconfig
    ftgl
    fzf
    fzy
    gcolor3
    gdk-pixbuf
    gdk-pixbuf-xlib
    gh
    gist
    git
    glib
    glibc
    gmime3
    gnome-disk-utility
    gnome-icon-theme
    gnome-keyring
    gnome-themes-extra
    gnome.gvfs
    gnutar
    gnutls
    gob2
    gobject-introspection
    gparted
    graphite2
    gsettings-desktop-schemas
    gthumb
    gtk2-x11
    gtk3
    gtk3-x11
    gtk4
    gtk_engines
    gusb
    htop
    imlib2Full
    inetutils
    jq
    kdePackages.breeze-icons
    killall
    libappindicator-gtk3
    libarchive
    libcanberra-gtk3 #system tool
    libdbusmenu
    libdbusmenu-gtk3
    libgnome-keyring
    libnotify
    libpeas
    libpeas2
    libpkgconf
    libtool
    libusb1
    libxdg_basedir
    lm_sensors
    lshw
    lz4
    massren
    mime-types
    minizip2
    moreutils
    mozlz4a
    mtools
    neofetch
    networkmanager
    networkmanagerapplet
    nix-init
    nmap
    ntfs3g
    ntfsprogs
    openssl
    ouch
    pango
    pangomm
    pastel
    pavucontrol
    pciutils
    perl538Packages.CairoGObject
    pinentry-tty
    pmutils
    polkit_gnome
    portaudio
    procps
    protobuf
    protobufc
    ps_mem
    psftools
    pulseaudio
    python312Packages.cairosvg
    python312Packages.py-dmidecode
    python312Packages.pyqt6
    python312Packages.qtpy
    rar
    rarcrack
    ripgrep-all
    rubyPackages.cairo-gobject
    rubyPackages.gdk_pixbuf2
    rubyPackages.gobject-introspection
    shared-mime-info
    silver-searcher
    smartmontools
    sops
    squashfs-tools-ng
    squashfsTools
    squashfuse
    ssh-to-age
    sysfsutils
    sysstat
    sysvtools
    sysz
    t1utils
    template-glib
    terminus_font #system tool
    testdisk
    trash-cli
    tree-sitter
    ttfautohint
    usbmuxd
    utillinux
    uutils-coreutils
    vgrep
    vimv
    vte-gtk4
    wget
    whois
    wirelesstools
    wmctrl
    wmic-bin
    wmutils-core
    wmutils-libwm
    wmutils-opt
    xarchiver
    xclip
    xdg-dbus-proxy
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-launch
    xdg-user-dirs
    xdg-utils
    xdgmenumaker
    xotool
    xgeometry-select
    xorg-rgb
    xorg.fontalias
    xorg.fonttosfnt
    xorg.fontutil
    xorg.libX11
    xorg.libxcb
    xorg.mkfontir
    xorg.xbacklight
    xorg.xcbutil
    xorg.xcbutilerrors
    xorg.xcbutilimage
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    xorg.xconsole
    xorg.xev
    xorg.xev
    xorg.xhost
    xorg.xinit
    xorg.xkill
    xorg.xorgproto
    xorg.xprop
    xorg.xwininfo
    xorg_sys_opengl
    xorriso
    xscreensaver
    xsecurelock
    xsettingsd
    xss-lock
    xz
    yamllint
    zip
    zlib
    zlib-ng
    zstd
  ];
}
