{ pkgs }:

with pkgs; [
  ascii-image-converter
  ciano
  figlet
  gifsicle 
  giflib
  gifski
  gimp-with-plugins
  gimpPlugins.exposureBlend
  gimpPlugins.fourier
  gimpPlugins.gap
  gimpPlugins.gimplensfun
  gimpPlugins.lightning
  gimpPlugins.lqrPlugin
  gimpPlugins.resynthesizer
  gimpPlugins.texturize
  gimpPlugins.waveletSharpen
  metadata-cleaner
  giph
  graphicsmagick
  image_optim
  imagemagick
  imgpatchtools
  imv
  inkscape-with-extensions
  jp2a
  jpegoptim
  krita
  libwebp
  meme
  nodePackages_latest.svgo
  optipng
  pinsel
  webp-pixbuf-loader
  rubyPackages.gdk_pixbuf2
  yeetgif
  jhead
  jpegoptim 
  jpegrescan
  pngout
  pngquant
  resvg
  emacsPackages.svgo  
  pngcrush
  python311Packages.pyfiglet
  svgcleaner
  toilet
  xcftools
]

