{pkgs, ...}:
with pkgs; [
  any-nix-shell
  awscli
  bash
  beautysh
  biber
  bibtex2html
  black
  brotli
  cached-nix-shell
  cargo
  cargo-binutils
  cbfmt
  chruby
  cmake
  cpp-hocon
  cpp-utilities
  cppclean
  cppdb
  cutter
  deadnix
  dejsonlz4
  direnv
  efm-langserver
  ejson
  ejson2env
  expat
  fclones
  fcppt
  flutter
  fuse3
  gdk-pixbuf
  gdk-pixbuf-xlib
  getopt
  getoptions
  git
  git-backup-go
  git-extras
  git-filter-repo
  git-ignore
  git-repo-updater
  git-revise
  git-trim
  gitleaks
  glib
  glow
  glxinfo
  gnumake
  gnutls
  go
  go-protobuf
  gofumpt
  gource
  icu
  imlib2Full
  ipfs
  ipfs
  ispell
  isync
  just
  kotlin
  kotlin-language-server
  kotlin-native
  ktlint
  libffi
  libimobiledevice
  libpkgconf
  libtiff
  libtool
  lightningcss
  lua
  lua-language-server
  lua51Packages.lgi
  lua51Packages.lua
  lua51Packages.luarocks-nix
  lua5_3_compat
  lua5_4_compat
  luabind
  luaformatter
  luajitPackages.busted
  luajitPackages.cqueues
  luajitPackages.dkjson
  luajitPackages.ldbus
  luajitPackages.ldoc
  luajitPackages.lgi
  luajitPackages.lpeg
  luajitPackages.lpeg_patterns
  luajitPackages.lpeglabel
  luajitPackages.lua
  luajitPackages.lua-curl
  luajitPackages.lua-lsp
  luajitPackages.lua-messagepack
  luajitPackages.lua-protobuf
  luajitPackages.lua-subprocess
  luajitPackages.luacheck
  luajitPackages.luarocks
  luajitPackages.luarocks-nix
  luajitPackages.luasocket
  luajitPackages.luasql-sqlite3
  luajitPackages.mediator_lua
  luajitPackages.mpack
  luajitPackages.std-_debug
  luajitPackages.std-normalize
  luajitPackages.stdlib
  luajitPackages.vicious
  luajitPackages.vusted
  luajitPackages.wrapLua
  lynis
  marksman
  mu
  ncdu
  neovim-unwrapped
  nil
  nix-init
  nix-tree
  nixpkgs-fmt
  node2nix
  nodePackages.prettier
  nodePackages_latest.diagnostic-languageserver
  nodePackages_latest.eslint
  nodePackages_latest.gulp
  nodePackages_latest.neovim
  nodejs
  nps
  nss
  nvd
  onefetch
  openjdk
  pandoc
  pandoc-lua-filters
  pciutils
  pet
  pkg-config
  pkg-config-unwrapped
  pkg-configUpstream
  prisma-engines
  protobuf
  protobufc
  puppeteer-cli
  python311Packages.PyICU
  python311Packages.brotlicffi
  python311Packages.brotlipy
  python311Packages.googleapis-common-protos
  python311Packages.mdformat
  python311Packages.protobuf
  python311Packages.pylsp-mypy
  python311Packages.websockets
  python311Packages.wheel
  ruby
  rustc
  rustfmt
  rustscan
  rustup
  sass
  sassc
  shellcheck
  shellharden
  shfmt
  skim
  sqlite
  sqlite-utils
  stdenv.cc.cc
  stylua
  sublime4
  sumneko-lua-language-server
  tectonic
  tokei
  tree-sitter
  typescript
  vim
  vim-vint
  vimPlugins.rust-tools-nvim
  wkhtmltopdf-bin
  xcftools
  xorg.libX11
  xorg_sys_opengl
  yarn
  yarn2nix
]
