{pkgs, ...}:
with pkgs; [
  #nodePackages_latest.neovim
  any-nix-shell
  brotli
  cached-nix-shell
  cargo
  cargo-binutils
  clang
  cmake
  deadnix
  direnv
  fuse3
  #  squashfs-tools-ng
  #  squashfsTools
  #  squashfuse
  getopt
  pixcat

  getoptions
  gettext
  git
  git-extras
  git-filter-repo
  git-ignore
  git-repo-updater
  git-revise
  git-trim
  gitleaks
  glib
  glow
  gnumake
  gnutls
  go
  gource
  imlib2Full
  inetutils
  just
  leptosfmt
  libclang
  libcxxStdenv
  libffi
  libglibutil
  libimobiledevice
  libpkgconf
  libtiff
  libtool
  lua
  lua-language-server
  lua5_3_compat
  lua5_4_compat
  luabind
  luaformatter
  luajitPackages.cqueues
  luajitPackages.inspect
  luajitPackages.ldbus
  luajitPackages.ldoc
  luajitPackages.lgi
  luajitPackages.lpeg
  luajitPackages.lpeg_patterns
  luajitPackages.lpeglabel
  luajitPackages.lua
  luajitPackages.lua-curl
  luajitPackages.lua-messagepack
  luajitPackages.lua-protobuf
  luajitPackages.lua-subprocess
  luajitPackages.luarocks-nix
  luajitPackages.luasocket
  luajitPackages.luasql-sqlite3
  luajitPackages.mediator_lua
  luajitPackages.mpack
  luajitPackages.std-_debug
  luajitPackages.std-normalize
  luajitPackages.stdlib
  luajitPackages.vicious
  luajitPackages.wrapLua
  lynis
  nil
  nix-init
  nix-tree
  nixpkgs-fmt
  node2nix
  nodenv
  nodePackages_latest.diagnostic-languageserver
  nodePackages_latest.gulp
  nodePackages_latest.nodejs
  nodePackages_latest.prettier
  nps
  nss
  nvd
  onefetch
  openjdk
  pandoc
  pandoc-lua-filters
  pciutils
  pet
  php
  php83Packages.composer
  pipx
  pkg-config
  poetry
  protobuf
  protobufc
  ruby
  rubyfmt
  rustc
  rustfmt
  rustscan
  rustup
  rustywind
  sass
  sassc
  shellcheck
  shellharden
  shfmt
  sqlite
  sqlite-utils
  stdenv.cc.cc
  stylua
  sumneko-lua-language-server
  tokei
  tree-sitter
  typescript
  wkhtmltopdf-bin
  xorg_sys_opengl
  xorg.libX11
  yamlfix
  yarn
  yarn2nix
  zlib
]
