{pkgs, ...}:
with pkgs; [
  #nodePackages_latest.neovim
  #nodePackages_latest.diagnostic-languageserver
  #nodePackages_latest.gulp
  #nodePackages_latest.nodejs
  #nodePackages_latest.prettier
  actionlint
  any-nix-shell
  bc
  bfg-repo-cleaner
  black
  brotli
  cached-nix-shell
  cargo
  cargo-binutils
  clang
  claude-code
  cloudflare-cli
  cmake
  commitlint-rs
  deadnix
  diagnostic-languageserver
  direnv
  dotenv-linter
  eslint_d
  fuse3
  gcc
  gccStdenv
  getopt
  getoptions
  gettext
  gist
  git
  git
  git-backup-go
  git-extras
  git-extras
  git-filter-repo
  git-filter-repo
  git-ignore
  git-lfs
  git-repo-updater
  git-repo-updater
  git-revise
  git-revise
  git-trim
  git-trim
  gitAndTools.gh
  gitAndTools.git-absorb
  gitAndTools.git-machete
  gitAndTools.gitui
  gitleaks
  gitleaks
  glib
  glow
  gnumake
  gnutls
  go
  go
  gopls
  gource
  grex
  hlint
  imlib2Full
  inetutils
  just
  latex2html
  leptosfmt
  libclang
  libcxxStdenv
  libffi
  libglibutil
  libimobiledevice
  libpkgconf
  libtiff
  libtool
  lldb
  lua
  lua-language-server
  lua51Packages.lua
  lua51Packages.luarocks
  lua5_1
  lua5_2
  lua5_2_compat
  lua5_3_compat
  lua5_4_compat
  luabind
  luaformatter
  luajitPackages.cqueues
  luajitPackages.inspect
  luajitPackages.ldbus
  luajitPackages.ldoc
  luajitPackages.lgi
  luajitPackages.lpeg
  luajitPackages.lpeg_patterns
  luajitPackages.lpeglabel
  luajitPackages.lua
  luajitPackages.lua
  luajitPackages.lua-curl
  luajitPackages.lua-messagepack
  luajitPackages.lua-protobuf
  luajitPackages.lua-subprocess
  luajitPackages.luarocks-nix
  luajitPackages.luasocket
  luajitPackages.luasql-sqlite3
  luajitPackages.mediator_lua
  luajitPackages.mpack
  luajitPackages.std-_debug
  luajitPackages.std-normalize
  luajitPackages.stdlib
  luajitPackages.vicious
  luajitPackages.wrapLua
  lynis
  markdownlint-cli2
  meson
  meson-tools
  nil
  nix-init
  nix-tree
  nixpkgs-fmt
  node2nix
  nodejs
  nodenv
  nps
  nss
  nvd
  onefetch
  openjdk
  pandoc
  pandoc-lua-filters
  pciutils
  pet
  php
  php83Packages.composer
  pipx
  pixcat
  pkg-config
  poetry
  protobuf
  protobufc
  pylint
  rmlint
  ruby
  rubyfmt
  rust-analyzer
  rustc
  rustfmt
  rustlings
  rustscan
  rustup
  rustywind
  sass
  sassc
  sassc
  shellcheck
  shellharden
  shfmt
  sqlite
  sqlite
  sqlite-analyzer
  sqlite-interactive
  sqlite-utils
  sqlite-utils
  sqlitebrowser
  stdenv.cc.cc
  stylua
  stylua
  sumneko-lua-language-server
  tailwindcss-language-server
  tokei
  tree-sitter
  typescript
  unstable.squashfs-tools-ng
  unstable.squashfsTools
  unstable.squashfuse
  usort
  usql
  vscode-langservers-extracted
  wkhtmltopdf-bin
  xorg.gccmakedep
  xorg.libX11
  xorg_sys_opengl
  yamllint
  yarn2nix
  zlib
]
