{pkgs, ...}:
with pkgs; [
  appimage-run
  appimagekit
  gnome.file-roller
  pantheon.file-roller-contract
  xarchiver
  archiver
  aspell
  aspellDicts.de
  aspellDicts.en
  aspellDicts.en-computers
  aspellDicts.en-science
  aspellDicts.hi
  codespell
  gspell
  gtkspell3
  gtkspellmm
  hunspell
  hunspellDicts.de_DE
  hunspellDicts.en_US-large
  hunspellDicts.es_MX
  mythes
  nuspell
  typos
  libusb
  gusb
  ibus-with-plugins
  pdf-parser
  poppler_utils
  leela
  ebook_tools
  pdfmm
  pdftag
  pdftk
  pdfstudio2022
  ocrmypdf
  termpdfpy
  updfparser
  python311Packages.pdftotext
  appstream-glib
  bitwarden
  bitwarden-cli
  bleachbit
  brave
  discord
  font-manager
  fuseiso
  gnome.gnome-disk-utility
  google-chrome
  gpick
  epiphany
  hunspell
  luakit
  networkmanagerapplet
  phinger-cursors
  tdesktop
  themechanger
  thunderbird
  tor-browser-bundle-bin
  vlc
  blueman
  galculator
  gparted
  xarchiver
  avidemux
  cairo
  cairomm
  dbus-broker
  xcolor
  epick
  eyedropper
  gpick
  xmcp
  dconf
  fbida
  feh
  geocode-glib_2
  glib
  glib-networking
  glibc
  glibc_memusage
  glibmm
  gnome.file-roller
  gnome.gnome-themes-extra
  gnome.gvfs
  gnome2.gtkglext
  gob2
  gobject-introspection-unwrapped
  goocanvas
  goocanvas3
  gthumb
  gtk-sharp-2_0
  gtk2-x11
  gtk3
  gtk3-x11
  gtk4
  gtk_engines
  gusb
  i3lock-color
  inotify-tools
  libcanberra-gtk3
  libdbusmenu
  libdbusmenu-gtk3
  libfm
  libfm-extra
  libgee
  libglibutil
  libgudev
  libinput
  libnotify
  libsForQt5.qt5ct
  libsForQt5.qtstyleplugin-kvantum
  libxdg_basedir
  lightlocker
  maim
  menu-cache
  mesa
  mesa-demos
  networkmanagerapplet
  pango
  pangomm
  papirus-folders
  papirus-icon-theme
  perl536Packages.CairoGObject
  perl536Packages.GooCanvas2CairoTypes
  pixcat
  polkit_gnome
  poppler_utils
  ranger
  rofi
  template-glib
  unrar
  unscd
  ventoy-full
  wirelesstools
  wmctrl
  wpa_supplicant
  xclip
  xdg-desktop-portal-gtk
  xdg-utils
  xdotool
  xfce.exo
  xfce.garcon
  xfce.libxfce4ui
  xfce.libxfce4util
  xfce.tumbler
  xfce.xfce4-dev-tools
  xfce.xfce4-settings
  xfce.xfconf
  xlsfonts
  acpi
  brightnessctl
  firefox
  fluent-icon-theme
  glibmm
  jpegoptim
  librsvg
  mozjpeg
  olive-editor
  openshot-qt
  pasystray
  picom
  python311Packages.pyxdg
  shotcut
  terminus-nerdfont
  terminus_font
  xorg.fontalias
  xorg.fonttosfnt
  xorg.fontutil
  xorg.libxcb
  xorg.mkfontdir
  xorg.xbacklight
  xorg.xcbutil
  xorg.xcbutilerrors
  xorg.xcbutilimage
  xorg.xcbutilrenderutil
  xorg.xcbutilwm
  xorg.xconsole
  xorg.xev
  xorg.xfontsel
  xorg.xinit
  xorg.xkill
  xorg.xorgproto
  xorg.xprop
  xorg.xwininfo
  xscreensaver
  xsecurelock
  xsuspender
  bitwarden
  discord
  epiphany
  font-manager
  giflib
  gifsicle
  gifski
  google-chrome
  inkscape-with-extensions
  librewolf
  meme
  pdfarranger
  signal-desktop
  tdesktop
  themechanger
  thunderbird-bin
  xcftools
  xorg.xhost
  xterm
  zathura
]
