{pkgs, ...}:
with pkgs; [
  babl
  colorstorm
  colorz
  curtail
  emacsPackages.svgo
  exiftool
  feh
  figlet
  gdk-pixbuf
  gif-for-cli
  giflib
  gifsicle
# unstable.gimp-with-plugins
  #gimpPlugins.bimp
  gimp 
  gimpPlugins.exposureBlend
  gimpPlugins.farbfeld
  gimpPlugins.fourier
 # gimpPlugins.gap
  gimpPlugins.gimplensfun
  gimpPlugins.gmic
  gimpPlugins.lightning
  gimpPlugins.lqrPlugin
  gimpPlugins.resynthesizer
  gimpPlugins.texturize
  gimpPlugins.waveletSharpen
    gmic
  inkscape-with-extensions
  graphicsmagick
  image_optim
  image-roll
  imagemagick
  img-cat
  imgcat
  imlib2-nox
  imlib2Full
  jpeginfo
  jpegoptim
  libexif
  libjpeg
  libpng
  librsvg
  libspng
  libwebp
  meme-image-generator
  metapixel
  mozjpeg
  nodePackages_latest.svgo
  optipng
  oxipng
  pixel2svg
  pixeluvo
  pngcrush
  pngtoico
  pngtools
  potrace
  python312Packages.colorthief
  python312Packages.pyfiglet
  python312Packages.pystache
  python312Packages.svgwrite
  pywal
  resvg
  svgcleaner
  t1utils
  termcolor
  upscaler
  upscayl
  upscayl-ncnn
  xcolor
  xcolor
  xorg-rgb
]
