{pkgs, ...}:
with pkgs; [
  ascii-image-converter
  ciano
  delve
  ebook_tools
  emacsPackages.svgo
  feh
  figlet
  giflib
  gifsicle
  gifski
  resvg
  exiftool
  labelImg
  libexif
  librsvg
  jpegoptim
  mozjpeg
  shotcut
  svgcleaner
  gimp
  gimp-with-plugins
  gimpPlugins.exposureBlend
  gimpPlugins.fourier
  gimpPlugins.gap
  gimpPlugins.gimplensfun
  gimpPlugins.lightning
  gimpPlugins.lqrPlugin
  gimpPlugins.resynthesizer
  gimpPlugins.texturize
  gimpPlugins.waveletSharpen
  giph
  graphicsmagick
  image_optim
  imagemagick
  imgpatchtools
  imv
  inkscape
  inkscape-with-extensions
  jhead
  jp2a
  jpegrescan
  krita
  libwebp
  meme
  metadata-cleaner
  nodePackages_latest.svgo
  optipng
  pinsel
  pngcrush
  pngout
  pngquant
  python311Packages.pyfiglet
  rubyPackages.gdk_pixbuf2
  toilet
  updfparser
  vlc
  webp-pixbuf-loader
  xcftools
  ascii-image-converter
  gifsicle
  jpegoptim
  emacsPackages.svgo
]
