{
  lib,
  pkgs,
  ...
}: {
  home.packages = lib.attrValues {
    inherit
      (pkgs)
      dbus-broker
      eggdbus
      midori
      bc
      bfg-repo-cleaner
      feh
      fzf
      gist
      git
      git-backup-go
      git-extras
      git-filter-repo
      git-lfs
      git-repo-updater
      git-revise
      git-trim
      gitleaks
      gnome-keyring
      go
      gopls
      grex
      i3lock-color
      imagemagick
      kbfs
      keybase
      keybase-gui
      keychain
      killall
      libgnome-keyring
      moreutils
      mpc-cli
      mpdris2
      obsidian
      pavucontrol
      playerctl
      pre-commit
    pcre2
      procps
      pywal
      rust-analyzer
      sassc
      slurp
      socat
      swww
      trash-cli
      wf-recorder
      xdg-desktop-portal
      ;
    inherit
      (pkgs.gitAndTools)
      gh
      git-absorb
      git-machete
      gitui
      ;
    inherit
      (pkgs.luaPackages)
      lua
      ;
    inherit
      (pkgs.xorg)
      xev
      ;
    pylsp = pkgs.python311.withPackages (p:
      with p; [
        flake8
        python-lsp-server
      ]);
  };
}
