{
  lib,
  pkgs,
  ...
}: {
  home.packages = lib.attrValues {
    inherit
      (pkgs)
      bfg-repo-cleaner
      black
      anytype
      cargo
      ccls
      clang
      clang-tools
      cmake
      colordiff
      delve
      gist
      git-filter-repo
      go
      gopls
      gpart
      grex
      kbfs
      keybase
      keybase-gui
      keychain
      lldb
      nodejs
      parted
      pre-commit
      rust-analyzer
      rustfmt
      selene
      shellcheck
      shfmt
      shiori
      sqlite
      stylua
      subversion
      sumneko-lua-language-server
      texlab
      uncrustify
      ;
    inherit
      (pkgs.gnome)
      gnome-keyring
      libgnome-keyring
      ;
    inherit
      (pkgs.gitAndTools)
      gh
      git-absorb
      git-machete
      gitui
      ;
    inherit
      (pkgs.luaPackages)
      lua
      ;

    inherit
      (pkgs.nodePackages_latest)
      jsonlint
      prettier
      typescript-language-server
      vscode-langservers-extracted
      yaml-language-server
      yarn
      ;

    pylsp = pkgs.python311.withPackages (p:
      with p; [
        flake8
        python-lsp-server
      ]);
  };
}
