{
  lib,
  pkgs,
  ...
}: {
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      android-tools
      android-udev-rules
      bash
      binutils
      curl
      gcc
      glib
      glibc
      gmime3
      icu
      libcanberra-gtk3
      libdbusmenu
      libdbusmenu-gtk3
      libfm
      libfm-extra
      libgccjit
      libgee
      libgig
      libgit2
      libgit2-glib
      libglibutil
      libgudev
      libimobiledevice
      libinput
      libisoburn
      libnotify
      librewolf
      librsvg
      libsForQt5.qt5ct
      libsecret
      libtiff
      libtool
      libunwind
      libuuid
      libxdg_basedir
      lightlocker
      luajitPackages.cjson
      luajitPackages.cqueues
      luajitPackages.dkjson
      luajitPackages.inspect
      luajitPackages.ldbus
      luajitPackages.ldoc
      luajitPackages.lgi
      luajitPackages.lpeg
      luajitPackages.lpeg_patterns
      luajitPackages.lpeglabel
      luajitPackages.lua
      luajitPackages.lua-curl
      luajitPackages.lua-lsp
      luajitPackages.lua-messagepack
      luajitPackages.lua-protobuf
      luajitPackages.lua-subprocess
      luajitPackages.luacheck
      luajitPackages.luarocks
      luajitPackages.luarocks-nix
      luajitPackages.luasocket
      luajitPackages.luasql-sqlite3
      luajitPackages.mediator_lua
      luajitPackages.mpack
      luajitPackages.std-_debug
      luajitPackages.std-normalize
      luajitPackages.stdlib
      luajitPackages.vicious
      luajitPackages.wrapLua
      openssl
      ranger
      sassc
      speechd
      stdenv.cc.cc
      util-linux
      xorg.libX11
      xsettingsd
      zlib
      zsh
    ];
  };
}
