{
  config,
  pkgs,
  lib,
  ...
}: {
  # Install these packages for my user
  home.packages = with pkgs; [
    _7zz
    #  qemu_full
    abootimg
    acpi
    adbfs-rootless
    advancecomp
    alejandra
    alsa-firmware
    alsa-lib
    alsa-oss
    alsa-plugins
    alsa-tools
    alsa-utils
    alsaequal
    amarena-theme
    android-backup-extractor
    android-file-transfer
    android-tools
    android-udev-rules
    any-nix-shell
    apkeep
    apkg
    apkid
    apkleaks
    apko
    apksigcopier
    apksigner
    apktool
    appimage-run
    appimagekit
    appindicator-sharp
    appstream
    appstream-glib
    appvm
    arandr
    archivemount
    archiver
    ardour
    arduino
    aria
    arj
    ark
    as-tree
    ascii-image-converter
    aspell
    aspellDicts.de
    aspellDicts.en
    aspellDicts.en-computers
    aspellDicts.en-science
    aspellDicts.hi
    audacity
    audio-recorder
    automake
    autorandr
    avfs
    avidemux
    awscli
    bash
    bat
    bdfresize
    beep
    biber
    bibtex2html
    bintools
    binutils
    bitwarden
    bitwarden-cli
    black
    bleachbit
    blueman
    bolt
    book-summary
    bottom
    brightnessctl
    btar
    btop
    bun
    bundletool
    busybox
    byzanz
    bzip2
    bzip3
    cached-nix-shell
    cairo
    cairomm
    calibre
    cargo
    cargo-binutils
    cava
    cbfmt
    ccls
    cheat
    chruby
    ciano
    cifs-utils
    clang
    clang-tools
    clangStdenv
    clipster
    cmake
    codec2
    codespell
    colordiff
    colorz
    comma
    commonsCompress
    conda
    conmon
    containerd
    containerpilot
    convfont
    convoy
    cookiecutter
    copier
    cpio
    cpp-hocon
    cpp-utilities
    cppclean
    cppdb
    crabz
    csv2latex
    cups
    curl
    curtail
    darling-dmg
    dbus
    dbus-broker
    dbus-glib
    dconf
    ddcui
    ddcutil
    deadnix
    deer
    dejsonlz4
    delve
    desktop-file-utils
    devbox
    dex2jar
    direnv
    discord
    distrobox
    dmg2img
    dnsutils
    docker
    docker-buildx
    docker-client
    docker-compose
    docker-credential-helpers
    docker-distribution
    docker-gc
    docker-slim
    dogdns
    dosfstools
    dtrx
    dupeguru
    easyeffects
    ebook_tools
    efficient-compression-tool
    efibootmgr
    efitools
    efm-langserver
    eggdbus
    ejson
    ejson2env
    electron
    element-desktop
    emacsPackages.svgo
    epick
    epiphany
    espeak
    exa
    exfatprogs
    exiftool
    expat
    extra-cmake-modules
    eyedropper
    eza
    fastjar
    fbida
    fcft
    fclones
    fcppt
    fd
    feh
    ffcast
    ffmpeg-full
    figlet
    file
    file-rename
    firefox
    flite
    flutter
    fntsample
    font-manager
    fontpreview
    freetts
    fuse3
    fuseiso
    fzf
    fzy
    galculator
    gallery-dl
    gammastep
    gcc
    gccStdenv
    gcolor3
    gdk-pixbuf
    gdk-pixbuf-xlib
    gdu
    geocode-glib_2
    getopt
    getoptions
    gh
    ghost
    ghostscript
    gi-docgen
    gibo
    gif-for-cli
    giflib
    gifsicle
    gimp
    gimp-with-plugins
    gimpPlugins.exposureBlend
    gimpPlugins.fourier
    gimpPlugins.gap
    gimpPlugins.gimplensfun
    gimpPlugins.lightning
    gimpPlugins.lqrPlugin
    gimpPlugins.resynthesizer
    gimpPlugins.texturize
    gimpPlugins.waveletSharpen
    gio-sharp
    gist
    git
    git-backup
    git-branchless
    git-extras
    git-filter-repo
    git-ignore
    git-repo-updater
    git-revise
    git-trim
    gitleaks
    gitui
    glances
    glib
    glib-networking
    glib-testing
    glibc
    glibc_memusage
    glibc_multi
    glibcInfo
    glibcLocalesUtf8
    glibmm
    gmime
    gmime3
    gnaural
    gnome.gnome-autoar
    gnome.gnome-disk-utility
    gnome.gnome-font-viewer
    gnome.gnome-sound-recorder
    gnome.gnome-themes-extra
    gnome.gvfs
    gnome.nixos-gsettings-overrides
    gnome2.gtkglext
    gnumake
    gnutar
    gnutls
    go
    gob2
    gobject-introspection
    gobject-introspection-unwrapped
    gofumpt
    goocanvas
    goocanvas3
    google-chrome
    gopls
    gource
    gpart
    gparted
    gpick
    gping
    graphicsmagick
    graphite2
    grex
    gsettings-desktop-schemas
    gsound
    gspell
    gst_all_1.gst-libav
    gthumb
    gtk_engines
    gtk-sharp-2_0
    gtk2-x11
    gtk2fontsel
    gtk3
    gtk3-x11
    gtk4
    gtkextra
    gtkspell3
    gtkspellmm
    gusb
    handlr
    hcloud
    hoard
    htop
    hue-cli
    hunspell
    hunspellDicts.de_DE
    hunspellDicts.en_US-large
    hunspellDicts.es_MX
    i3lock-color
    ibus-with-plugins
    icu
    image_optim
    imagemagick
    imgcat
    imgpatchtools
    imgurbash2
    imlib2-nox
    imlib2Full
    imv
    inkscape
    inkscape-with-extensions
    inotify-tools
    iperf3
    ipfs
    ipu6ep-camera-bin
    ispell
    isync
    iw
    jdupes
    jhead
    jp2a
    jpegexiforient
    jpeginfo
    jpegoptim
    jpegrescan
    jq
    julia
    just
    kbfs
    keybase
    keybase-gui
    keychain
    kooha
    krita
    ktlint
    kvmtool
    labelImg
    latex2html
    latexrun
    lcdf-typetools
    leela
    libappindicator
    libappindicator-gtk3
    libarchive
    libcanberra-gtk3
    libdbusmenu
    libdbusmenu-gtk3
    libdevil-nox
    libexif
    libffi
    libfm
    libfm-extra
    libgccjit
    libgee
    libgig
    libgit2
    libgit2-glib
    libglibutil
    libgudev
    libimobiledevice
    libinput
    libjpeg
    libnfc
    libnotify
    libpar2
    libpkgconf
    libpng
    libpulseaudio
    librewolf
    librsvg
    libsForQt5.kio-gdrive
    libsForQt5.qt5ct
    libsForQt5.qtstyleplugins
    libspng
    libtiff
    libtool
    libungif
    libusb
    libuv
    libwebcam
    libwebp
    libxdg_basedir
    lightlocker
    lightningcss
    linuxConsoleTools
    lldb
    lm_sensors
    lmms
    logseq
    lrzip
    lshw
    lua
    lua-language-server
    lua5_3_compat
    lua5_4_compat
    lua51Packages.inspect
    lua51Packages.lgi
    lua51Packages.stdlib
    lua52Packages.inspect
    luabind
    luaformatter
    luajitPackages.busted
    luajitPackages.cqueues
    luajitPackages.dkjson
    luajitPackages.inspect
    luajitPackages.ldbus
    luajitPackages.ldoc
    luajitPackages.lgi
    luajitPackages.libluv
    luajitPackages.lpeg
    luajitPackages.lpeg_patterns
    luajitPackages.lpeglabel
    luajitPackages.lua
    luajitPackages.lua-curl
    luajitPackages.lua-lsp
    luajitPackages.lua-messagepack
    luajitPackages.lua-protobuf
    luajitPackages.lua-subprocess
    luajitPackages.luacheck
    luajitPackages.luarocks
    luajitPackages.luarocks-nix
    luajitPackages.luasocket
    luajitPackages.luasql-sqlite3
    luajitPackages.mediator_lua
    luajitPackages.mpack
    luajitPackages.sqlite
    luajitPackages.std-_debug
    luajitPackages.std-normalize
    luajitPackages.stdlib
    luajitPackages.vicious
    luajitPackages.vusted
    luajitPackages.wrapLua
    luakit
    lynis
    lz4
    lzma
    maim
    man-pages
    man-pages-posix
    manix
    manuskript
    marksman
    mdbook
    mdds
    mediainfo
    meme
    menu-cache
    menyoki
    mesa
    mesa-demos
    meson
    metadata-cleaner
    mime-types
    mimetic
    minizip2
    mjpegtoolsFull
    mnamer
    moreutils
    mozjpeg
    mozlz4a
    mpc_cli
    mpd
    mpd-discord-rpc
    mpd-mpris
    mpdevil
    mpv
    msieve
    mu
    mupdf
    mythes
    nanotts
    ncdu
    ncompress
    neofetch
    neovim-unwrapped
    nerd-font-patcher
    networkmanager
    networkmanagerapplet
    ngrok
    nil
    nix-binary-cache
    nix-bundle
    nix-direnv-flakes
    nix-index
    nix-init
    nix-plugins
    nix-prefetch
    nix-prefetch-scripts
    nix-template
    nix-tree
    nix-universal-prefetch
    nix-zsh-completions
    nixfmt
    nixos-generators
    nixpkgs-fmt
    nmap
    node2nix
    nodejs
    nodePackages_latest.diagnostic-languageserver
    nodePackages_latest.eslint
    nodePackages_latest.gulp
    nodePackages_latest.neovim
    nodePackages_latest.svgo
    nodePackages_latest.vscode-json-languageserver-bin
    nodePackages.prettier
    nox
    nps
    nss
    ntfs3g
    nurl
    nuspell
    nvd
    obs-studio
    obs-studio-plugins.input-overlay
    obs-studio-plugins.looking-glass-obs
    obs-studio-plugins.obs-backgroundremoval
    obs-studio-plugins.obs-gstreamer
    obs-studio-plugins.obs-move-transition
    obs-studio-plugins.obs-pipewire-audio-capture
    obs-studio-plugins.obs-source-record
    ocl-icd
    ocrmypdf
    onefetch
    opencl-clang
    openjdk
    openshot-qt
    openssl
    optipng
    ouch
    owncloud-client
    oxipng
    oxker
    p7zip
    pamixer
    pandoc
    pandoc-lua-filters
    pango
    pangomm
    pantheon.granite
    papirus-folders
    papirus-icon-theme
    parallel
    parcellite
    parted
    pasystray
    patchelf
    pavucontrol
    pbzip2
    pciutils
    pcre
    pcre-cpp
    pcre2
    pdf-parser
    pdfarranger
    pdftag
    pdftk
    peek
    perl536Packages.CairoGObject
    perl536Packages.GooCanvas2CairoTypes
    pet
    pfetch
    phinger-cursors
    picom
    picotts
    pigz
    pipewire
    pixcat
    pixz
    pkg-config
    pkg-config-unwrapped
    pkg-configUpstream
    platinum-searcher
    plzip
    pmutils
    pngcheck
    pngcrush
    pngloss
    pngnq
    pngout
    pngpp
    pngquant
    pngtoico
    pngtools
    polkit_gnome
    poppler_gi
    poppler_utils
    potrace
    power-profiles-daemon
    pre-commit
    premake
    prisma-engines
    ps_mem
    psftools
    psmisc
    pulseaudio
    pulseaudio-ctl
    pulseaudioFull
    pulseeffects-legacy
    pulsemixer
    puppeteer-cli
    pxz
    python311
    python311Packages.colorthief
    python311Packages.pdftotext
    python311Packages.pyfiglet
    python311Packages.pygccxml
    python311Packages.pygobject3
    python311Packages.PyICU
    python311Packages.pystache
    python311Packages.pyxdg
    python311Packages.websockets
    python311Packages.wheel
    qemu
    qpaeq
    qrencode
    qt5ct
    qt6.qt5compat
    qtcurve
    qtractor
    quark-engine
    ranger
    rar
    rarcrack
    rclone
    rcshist
    renameutils
    rep-gtk
    reposurgeon
    restic
    resvg
    ripgrep
    ripgrep-all
    rnix-lsp
    rocmPackages.clang-ocl
    rofi
    ruby
    rubyPackages.cairo-gobject
    rubyPackages.gdk_pixbuf2
    rubyPackages.gobject-introspection
    runzip
    rust-analyzer
    rustc
    rustfmt
    rustscan
    rustup
    sass
    sassc
    scdl
    scribus
    sdbus-cpp
    selene
    shared-mime-info
    shellcheck
    shellharden
    shfmt
    shiori
    shotcut
    silver-searcher
    simg2img
    simpleTpmPk11
    skim
    slop
    smartmontools
    snappy
    snzip
    solaar
    soundconverter
    soundfont-fluid
    soundfont-generaluser
    spotify
    sqlite
    sqlite-utils
    squashfs-tools-ng
    squashfsTools
    squashfuse
    sssd
    star-history
    stdenv.cc.cc
    stylua
    sublime4
    subversion
    suitesparse
    sumneko-lua-language-server
    svgcleaner
    svox
    swtpm
    swtpm-tpm2
    sysz
    t1lib
    t1utils
    tarlz
    tbb
    tdesktop
    tealdeer
    tectonic
    template-glib
    termcolor
    terminus_font
    terminus-nerdfont
    terraform
    testdisk
    texlab
    texlive.combined.scheme-full
    themechanger
    thunderbird-bin
    toilet
    tokei
    tor
    tor-browser-bundle-bin
    toybox
    tpm-tools
    tpm2-tools
    tpm2-tss
    tpmmanager
    transmission-gtk
    trash-cli
    tree
    tree-sitter
    tree-sitter-grammars.tree-sitter-bash
    tree-sitter-grammars.tree-sitter-bibtex
    tree-sitter-grammars.tree-sitter-c
    tree-sitter-grammars.tree-sitter-c-sharp
    tree-sitter-grammars.tree-sitter-clojure
    tree-sitter-grammars.tree-sitter-cmake
    tree-sitter-grammars.tree-sitter-comment
    tree-sitter-grammars.tree-sitter-commonlisp
    tree-sitter-grammars.tree-sitter-cpp
    tree-sitter-grammars.tree-sitter-css
    tree-sitter-grammars.tree-sitter-cuda
    tree-sitter-grammars.tree-sitter-dart
    tree-sitter-grammars.tree-sitter-devicetree
    tree-sitter-grammars.tree-sitter-dockerfile
    tree-sitter-grammars.tree-sitter-dot
    tree-sitter-grammars.tree-sitter-elisp
    tree-sitter-grammars.tree-sitter-embedded-template
    tree-sitter-grammars.tree-sitter-fennel
    tree-sitter-grammars.tree-sitter-fortran
    tree-sitter-grammars.tree-sitter-glsl
    tree-sitter-grammars.tree-sitter-go
    tree-sitter-grammars.tree-sitter-godot-resource
    tree-sitter-grammars.tree-sitter-gomod
    tree-sitter-grammars.tree-sitter-gowork
    tree-sitter-grammars.tree-sitter-graphql
    tree-sitter-grammars.tree-sitter-html
    tree-sitter-grammars.tree-sitter-http
    tree-sitter-grammars.tree-sitter-java
    tree-sitter-grammars.tree-sitter-javascript
    tree-sitter-grammars.tree-sitter-jsdoc
    tree-sitter-grammars.tree-sitter-json
    tree-sitter-grammars.tree-sitter-json5
    tree-sitter-grammars.tree-sitter-kotlin
    tree-sitter-grammars.tree-sitter-latex
    tree-sitter-grammars.tree-sitter-llvm
    tree-sitter-grammars.tree-sitter-lua
    tree-sitter-grammars.tree-sitter-make
    tree-sitter-grammars.tree-sitter-markdown
    tree-sitter-grammars.tree-sitter-markdown-inline
    tree-sitter-grammars.tree-sitter-nix
    tree-sitter-grammars.tree-sitter-ocaml
    tree-sitter-grammars.tree-sitter-ocaml-interface
    tree-sitter-grammars.tree-sitter-org-nvim
    tree-sitter-grammars.tree-sitter-perl
    tree-sitter-grammars.tree-sitter-php
    tree-sitter-grammars.tree-sitter-python
    tree-sitter-grammars.tree-sitter-regex
    tree-sitter-grammars.tree-sitter-ruby
    tree-sitter-grammars.tree-sitter-rust
    tree-sitter-grammars.tree-sitter-scheme
    tree-sitter-grammars.tree-sitter-scss
    tree-sitter-grammars.tree-sitter-sql
    tree-sitter-grammars.tree-sitter-toml
    tree-sitter-grammars.tree-sitter-tsq
    tree-sitter-grammars.tree-sitter-tsx
    tree-sitter-grammars.tree-sitter-typescript
    tree-sitter-grammars.tree-sitter-vim
    tree-sitter-grammars.tree-sitter-vue
    tree-sitter-grammars.tree-sitter-yaml
    ttfautohint
    ttfautohint-nox
    typescript
    typos
    ucl
    ueberzug
    uncrustify
    unrar
    unscd
    unzip
    updfparser
    usbmuxd
    usbutils
    utillinux
    ventoy-full
    video2midi
    vim
    vim-vint
    vimPlugins.nvim-treesitter
    vimPlugins.nvim-treesitter-context
    vimPlugins.nvim-treesitter-pyfold
    vimPlugins.nvim-treesitter-refactor
    vimPlugins.nvim-treesitter-textobjects
    vimPlugins.rust-tools-nvim
    vimv
    virt-manager
    virtmanager
    vlc
    vte-gtk4
    wait-for-build
    webp-pixbuf-loader
    wget
    whois
    wireguard-go
    wireguard-tools
    wirelesstools
    wkhtmltopdf-bin
    wmctrl
    wmutils-core
    wmutils-libwm
    wmutils-opt
    woff2
    wpa_supplicant
    x11docker
    xarchiver
    xbrightness
    xcbutilxrm
    xcftools
    xclip
    xcolor
    xdg-dbus-proxy
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-launch
    xdg-user-dirs
    xdg-utils
    xdgmenumaker
    xdotool
    xfce.exo
    xfce.garcon
    xfce.libxfce4ui
    xfce.libxfce4util
    xfce.thunar
    xfce.tumbler
    xfce.xfce4-dev-tools
    xfce.xfce4-power-manager
    xfce.xfce4-settings
    xfce.xfconf
    xfontsel
    xlsfonts
    xmcp
    xorg-rgb
    xorg.fontalias
    xorg.fonttosfnt
    xorg.fontutil
    xorg.gccmakedep
    xorg.libX11
    xorg.libxcb
    xorg.libXxf86dga
    xorg.libXxf86misc
    xorg.libXxf86vm
    xorg.mkfontdir
    xorg.xbacklight
    xorg.xcbutil
    xorg.xcbutilerrors
    xorg.xcbutilimage
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    xorg.xconsole
    xorg.xev
    xorg.xf86videoamdgpu
    xorg.xfontsel
    xorg.xhost
    xorg.xinit
    xorg.xkill
    xorg.xorgproto
    xorg.xprop
    xorg.xwininfo
    xournal
    xscreensaver
    xsecurelock
    xsettingsd
    xssproxy
    xsuspender
    xterm
    xxHash
    xz
    yad
    yakuake
    yamlfix
    yarn
    yarn2nix
    yeetgif
    yt-dlp
    yubioath-flutter
    zarchive
    zathura
    zip
    zlib
    zlib-ng
    zoom-us
    zplug
    zsh
    zsh-autocomplete
    zsh-edit
    zsh-navigation-tools
    zsh-you-should-use
    zstd
    zsync
    zziplib
  ];

  tlh.programs = {
    foot.enable = true;
    git.enable = true;
    htop.enable = true;
    python.enable = true;
    vim.enable = true;
    vscode.enable = true;
    zsh.enable = true;
  };

  # Imports
  imports = [
    ../colorscheme.nix
    ../modules/kitty
    ../modules/git
    ../modules/nvim
    ../modules/python
    ../modules/vscode
    ../modules/zsh
    ../modules/htop
    ../modules/sway
    ../modules/swaylock
    ../modules/waybar
  ];
  fonts.fontconfig.enable = true;
  services.gnome-keyring = {enable = true;};
  # Java Environment
  java = {
    enable = true;
    package = pkgs.jre;
  };
  # gnome's keyring manager
  seahorse.enable = true;

  # help manage android devices via command line
  adb.enable = true;

  # networkmanager tray uility
  nm-applet.enable = false;

  # allow users to mount fuse filesystems with allow_other
  fuse.userAllowOther = true;

  thunar = {
    enable = true;
    plugins = [
      pkgs.xfce.thunar-archive-plugin
      pkgs.xfce.thunar-volman
      pkgs.xfce.thunar-dropbox-plugin
      pkgs.xfce.thunar-media-tags-plugin
    ];
  };

  # Include man-pages
  manual.manpages.enable = true;

  # tells you the package that provides a command
  programs.command-not-found.enable = true;

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # Allow "unfree" licenced packages
  nixpkgs.config = {
    allowUnfree = true;
  };

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "23.05";
}
